pipeline {
    agent any

    
    stages {
        stage('Build') {
            steps {
		withGradle(){
                bat 'gradle clean build'}
            }}
        
        stage('Unit Tests') {
            steps {
		withGradle(){
                bat 'gradle test'}
            }}
            }
            post {
                always {
                    junit '**/build/test-results/test/TEST-*.xml'
                }}
        
       
        
}
